// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGxU66kSP-AtVUiFSZogd6yN9iCGQmQ8',
    appId: '1:169004896744:web:e5d517a3fe5d61a891945d',
    messagingSenderId: '169004896744',
    projectId: 'gate-pass-automation',
    authDomain: 'gate-pass-automation.firebaseapp.com',
    storageBucket: 'gate-pass-automation.firebasestorage.app',
    measurementId: 'G-6103QWK574',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0reRWlHoUS-tFKPqV5zj9yrh56K70BcQ',
    appId: '1:169004896744:android:cced7dea9523fa6e91945d',
    messagingSenderId: '169004896744',
    projectId: 'gate-pass-automation',
    storageBucket: 'gate-pass-automation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYugSFx6EIaYfJTE7yvM9q1_OTd2LxS8',
    appId: '1:169004896744:ios:dace2530aa30e0ce91945d',
    messagingSenderId: '169004896744',
    projectId: 'gate-pass-automation',
    storageBucket: 'gate-pass-automation.firebasestorage.app',
    iosBundleId: 'com.example.newGatepassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYugSFx6EIaYfJTE7yvM9q1_OTd2LxS8',
    appId: '1:169004896744:ios:dace2530aa30e0ce91945d',
    messagingSenderId: '169004896744',
    projectId: 'gate-pass-automation',
    storageBucket: 'gate-pass-automation.firebasestorage.app',
    iosBundleId: 'com.example.newGatepassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHGxU66kSP-AtVUiFSZogd6yN9iCGQmQ8',
    appId: '1:169004896744:web:26927c7e3ce9d89c91945d',
    messagingSenderId: '169004896744',
    projectId: 'gate-pass-automation',
    authDomain: 'gate-pass-automation.firebaseapp.com',
    storageBucket: 'gate-pass-automation.firebasestorage.app',
    measurementId: 'G-522F4TC8MG',
  );
}
